"""Initial migration

Revision ID: 8e8ef2c66cff
Revises: 
Create Date: 2023-04-11 20:58:44.590621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8ef2c66cff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=7), nullable=True),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('carrera', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('telefono', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefono')
    )
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alumnos_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_alumnos_matricula'), ['matricula'], unique=True)

    op.create_table('profesores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_empleado', sa.String(length=6), nullable=True),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('carrera', sa.String(length=64), nullable=True),
    sa.Column('telefono', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefono')
    )
    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profesores_no_empleado'), ['no_empleado'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profesores_no_empleado'))

    op.drop_table('profesores')
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alumnos_matricula'))
        batch_op.drop_index(batch_op.f('ix_alumnos_email'))

    op.drop_table('alumnos')
    # ### end Alembic commands ###
